
# Enable C support
language: c
# Compiler selection
compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && SYSD-DWITH_SYSTEMD=OFF"
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9 && SYSD-DWITH_SYSTEMD=ON"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && SYSD=-DWITH_SYSTEMD=OFF"
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && SYSD=-DWITH_SYSTEMD=ON"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && SYSD=-DWITH_SYSTEMD=OFF"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && SYSD=-DWITH_SYSTEMD=ON"


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y systemd libsystemd-daemon-dev
before_script:
  - pwd
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release $SYSD ..
  - make
  - cd ..
script: "sudo sh ./.travis-build.sh"
