
# Enable C support
language: c
# Compiler selection
compiler:
    - gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsystemd-daemon-dev
before_script:
  - pwd
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - cd ..
script: "sudo sh ./.travis-build.sh"
