Document: rikerio
Title: Debian rikerio Manual
Author: <insert document author here>
Abstract: This manual describes what rikerio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rikerio/rikerio.sgml.gz

Format: postscript
Files: /usr/share/doc/rikerio/rikerio.ps.gz

Format: text
Files: /usr/share/doc/rikerio/rikerio.text.gz

Format: HTML
Index: /usr/share/doc/rikerio/html/index.html
Files: /usr/share/doc/rikerio/html/*.html
