/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractStubServer : public jsonrpc::AbstractServer<AbstractStubServer>
{
public:
    AbstractStubServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<AbstractStubServer>(conn, type)
    {
        this->bindAndAddMethod(jsonrpc::Procedure("master.register", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "name", jsonrpc::JSON_STRING, "pid", jsonrpc::JSON_INTEGER, NULL), &AbstractStubServer::master_registerI);
        this->bindAndAddMethod(jsonrpc::Procedure("master.unregister", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "token", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::master_unregisterI);
        this->bindAndAddMethod(jsonrpc::Procedure("master.list", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &AbstractStubServer::master_listI);
        this->bindAndAddMethod(jsonrpc::Procedure("alloc", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "size", jsonrpc::JSON_INTEGER, "token", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::allocI);
        this->bindAndAddMethod(jsonrpc::Procedure("dealloc", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "offset", jsonrpc::JSON_INTEGER, "token", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::deallocI);
        this->bindAndAddMethod(jsonrpc::Procedure("data.create", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "data", jsonrpc::JSON_OBJECT, "id", jsonrpc::JSON_STRING, "token", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::data_createI);
        this->bindAndAddMethod(jsonrpc::Procedure("data.remove", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "id", jsonrpc::JSON_STRING, "token", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::data_removeI);
        this->bindAndAddMethod(jsonrpc::Procedure("data.list", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "id", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::data_listI);
        this->bindAndAddMethod(jsonrpc::Procedure("data.get", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "id", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::data_getI);
        this->bindAndAddMethod(jsonrpc::Procedure("link.add", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "dataId", jsonrpc::JSON_STRING, "linkId", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::link_addI);
        this->bindAndAddMethod(jsonrpc::Procedure("link.remove", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "dataId", jsonrpc::JSON_STRING, "linkId", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::link_removeI);
        this->bindAndAddMethod(jsonrpc::Procedure("link.list", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "pattern", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::link_listI);
        this->bindAndAddMethod(jsonrpc::Procedure("link.get", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "id", jsonrpc::JSON_STRING, NULL), &AbstractStubServer::link_getI);
    }

    inline virtual void master_registerI(const Json::Value &request, Json::Value &response)
    {
        response = this->master_register(request["name"].asString(), request["pid"].asInt());
    }
    inline virtual void master_unregisterI(const Json::Value &request, Json::Value &response)
    {
        response = this->master_unregister(request["token"].asString());
    }
    inline virtual void master_listI(const Json::Value &/*request*/, Json::Value &response)
    {
        response = this->master_list();
    }
    inline virtual void allocI(const Json::Value &request, Json::Value &response)
    {
        response = this->alloc(request["size"].asInt(), request["token"].asString());
    }
    inline virtual void deallocI(const Json::Value &request, Json::Value &response)
    {
        response = this->dealloc(request["offset"].asInt(), request["token"].asString());
    }
    inline virtual void data_createI(const Json::Value &request, Json::Value &response)
    {
        response = this->data_create(request["data"], request["id"].asString(), request["token"].asString());
    }
    inline virtual void data_removeI(const Json::Value &request, Json::Value &response)
    {
        response = this->data_remove(request["id"].asString(), request["token"].asString());
    }
    inline virtual void data_listI(const Json::Value &request, Json::Value &response)
    {
        response = this->data_list(request["id"].asString());
    }
    inline virtual void data_getI(const Json::Value &request, Json::Value &response)
    {
        response = this->data_get(request["id"].asString());
    }
    inline virtual void link_addI(const Json::Value &request, Json::Value &response)
    {
        response = this->link_add(request["dataId"].asString(), request["linkId"].asString());
    }
    inline virtual void link_removeI(const Json::Value &request, Json::Value &response)
    {
        response = this->link_remove(request["dataId"].asString(), request["linkId"].asString());
    }
    inline virtual void link_listI(const Json::Value &request, Json::Value &response)
    {
        response = this->link_list(request["pattern"].asString());
    }
    inline virtual void link_getI(const Json::Value &request, Json::Value &response)
    {
        response = this->link_get(request["id"].asString());
    }
    virtual Json::Value master_register(const std::string& name, int pid) = 0;
    virtual Json::Value master_unregister(const std::string& token) = 0;
    virtual Json::Value master_list() = 0;
    virtual Json::Value alloc(int size, const std::string& token) = 0;
    virtual Json::Value dealloc(int offset, const std::string& token) = 0;
    virtual Json::Value data_create(const Json::Value& data, const std::string& id, const std::string& token) = 0;
    virtual Json::Value data_remove(const std::string& id, const std::string& token) = 0;
    virtual Json::Value data_list(const std::string& id) = 0;
    virtual Json::Value data_get(const std::string& id) = 0;
    virtual Json::Value link_add(const std::string& dataId, const std::string& linkId) = 0;
    virtual Json::Value link_remove(const std::string& dataId, const std::string& linkId) = 0;
    virtual Json::Value link_list(const std::string& pattern) = 0;
    virtual Json::Value link_get(const std::string& id) = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_
